---
name: 01-02 Basic Docker Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-image:
    name: Build and push imagen Docker
    runs-on: ubuntu-latest
    steps:
      - name: verify content repo
        run: ls -la
      - name: Login in Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Build
        uses: docker/build-push-action@v6
        with:
          context: ./git-workflow-practice
          file: ./git-workflow-practice/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: rober0010/mi-nginx-custom:new

