---
name: 02 Build with BuildKit Cache

on:
  push:
    paths:
      - 'git-workflow-cache/**'
    branches:
      - main
  pull_request:
    paths:
      - 'git-workflow-cache/**'

jobs:
  build-image-cache:
    name: Build Image with Cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx (construye cache)
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build with cache
        uses: docker/build-push-action@v6
        with:
          context: ./git-workflow-cache
          file: ./git-workflow-cache/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: rober0010/mi-nginx-custom:cache
          cache-from: type=gha
          cache-to: type=gha,mode=max
